In [0]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

E: Package 'python-software-properties' has no installation candidate
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 110851 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.1-0ubuntu3~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.1-0ubuntu3~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.1-0ubuntu3~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=ht

In [0]:
!ls

adc.json  sample_data


In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [0]:
cd drive/Houston/

/content/drive/Houston


In [0]:
import numpy as np
import cv2

In [0]:
area_hsi = []
for i in range(3):
    for j in range(14):
        img_path = "area/pc_area_" + str(i) + "_" + str(j) + ".png"
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        area_hsi.append(img)
        
area_hsi = np.array(area_hsi)

In [0]:
area_lidar = []
for i in range(14):
    img_path = "area/lidar_area_" + str(i) + ".png"
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    area_lidar.append(img)

area_lidar = np.array(area_lidar)

In [0]:
print(area_hsi.shape)
print(area_lidar.shape)

(42, 349, 1905)
(14, 349, 1905)


In [0]:
train_file_name = "labels/train.txt"
test_file_name = "labels/test.txt"

In [0]:
file = open(train_file_name)
triplets = file.read().split()
for i in range(0, len(triplets)):
    triplets[i] = triplets[i].split(",")
train_array = np.array(triplets, dtype=int)
file.close()


file = open(test_file_name)
triplets = file.read().split()
for i in range(0, len(triplets)):
    triplets[i] = triplets[i].split(",")
test_array = np.array(triplets, dtype=int)
file.close()

HEIGHT = train_array.shape[0]
WIDTH = train_array.shape[1]

In [0]:
area_hsi_train_data = []
area_hsi_test_data = []
area_lidar_train_data = []
area_lidar_test_data = []
moment_hsi_train_data = []
moment_hsi_test_data = []
moment_lidar_train_data = []
moment_lidar_test_data = []
train_labels = []
test_labels = []
for i in range(HEIGHT):
    for j in range(WIDTH):
        if train_array[i, j] != 0:
            area_hsi_train_data.append(area_hsi[:, i, j])
            area_lidar_train_data.append(area_lidar[:, i, j])
            train_labels.append(train_array[i, j])
        if test_array[i,j] != 0:
            area_hsi_test_data.append(area_hsi[:, i, j])
            area_lidar_test_data.append(area_lidar[:, i, j])
            test_labels.append(test_array[i, j])

In [0]:
area_hsi_train_data = np.array(area_hsi_train_data)
area_hsi_test_data = np.array(area_hsi_test_data)
area_lidar_train_data = np.array(area_lidar_train_data)
area_lidar_test_data = np.array(area_lidar_test_data)
train_labels = np.array(train_labels)
test_labels = np.array(test_labels)

In [0]:
print(area_hsi_train_data.shape)
print(area_hsi_test_data.shape)
print(area_lidar_train_data.shape)
print(area_lidar_test_data.shape)
print(train_labels.shape)
print(test_labels.shape)

(2832, 42)
(12197, 42)
(2832, 14)
(12197, 14)
(2832,)
(12197,)


In [0]:
import keras

train_one_hot = keras.utils.to_categorical(train_labels-1)
test_one_hot = keras.utils.to_categorical(test_labels-1)

Using TensorFlow backend.


In [0]:
print(train_one_hot.shape)
print(test_one_hot.shape)
print(train_one_hot.shape)
print(test_one_hot.shape)

(2832, 15)
(12197, 15)
(2832, 15)
(12197, 15)


In [0]:
HSI_PATCH_SIZE = 27
LiDAR_PATCH_SIZE = 41
CONV1 = 500
CONV2 = 100
FC1 = 200
FC2 = 84
LEARNING_RATE = 0.005
BATCH_SIZE = 25

In [0]:
import numpy as np
padded_area_hsi = np.lib.pad(area_hsi, ((0,0), (HSI_PATCH_SIZE//2, HSI_PATCH_SIZE//2), (HSI_PATCH_SIZE//2,HSI_PATCH_SIZE//2)), 'reflect')
padded_area_lidar = np.lib.pad(area_lidar, ((0,0), (LiDAR_PATCH_SIZE//2, LiDAR_PATCH_SIZE//2), (LiDAR_PATCH_SIZE//2,LiDAR_PATCH_SIZE//2)), 'reflect')

In [0]:
print(padded_area_hsi.shape)
print(padded_area_lidar.shape)

(42, 375, 1931)
(14, 389, 1945)


In [0]:
def get_patches(data, patch_size, row, column):
  offset = patch_size // 2
  row_low = row - offset
  row_high = row + offset
  col_low = column - offset
  col_high = column + offset
  return data[0:, row_low:row_high + 1, col_low:col_high + 1].reshape(patch_size, patch_size, data.shape[0])

In [0]:
area_hsi_train_patches = []
area_hsi_test_patches = []
area_lidar_train_patches = []
area_lidar_test_patches = []

for i in range(HEIGHT):
  for j in range(WIDTH):
    if train_array[i, j] != 0:
      area_hsi_train_patches.append(get_patches(padded_area_hsi, HSI_PATCH_SIZE, i+HSI_PATCH_SIZE//2, j+HSI_PATCH_SIZE//2))
      area_lidar_train_patches.append(get_patches(padded_area_lidar, LiDAR_PATCH_SIZE, i+LiDAR_PATCH_SIZE//2, j+LiDAR_PATCH_SIZE//2))
    if test_array[i, j] != 0:
      area_hsi_test_patches.append(get_patches(padded_area_hsi, HSI_PATCH_SIZE, i+HSI_PATCH_SIZE//2, j+HSI_PATCH_SIZE//2))
      area_lidar_test_patches.append(get_patches(padded_area_lidar, LiDAR_PATCH_SIZE, i+LiDAR_PATCH_SIZE//2, j+LiDAR_PATCH_SIZE//2))

In [0]:
area_hsi_train_patches = np.array(area_hsi_train_patches)
area_hsi_test_patches = np.array(area_hsi_test_patches)
area_lidar_train_patches = np.array(area_lidar_train_patches)
area_lidar_test_patches = np.array(area_lidar_test_patches)

In [0]:
print(area_hsi_train_patches.shape)
print(area_hsi_test_patches.shape)
print(area_lidar_train_patches.shape)
print(area_lidar_test_patches.shape)

(2832, 27, 27, 42)
(12197, 27, 27, 42)
(2832, 41, 41, 14)
(12197, 41, 41, 14)


In [0]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D, Dense, Flatten
from tensorflow.python.keras.layers import InputLayer
from tensorflow.python.keras.layers import  MaxPooling2D
from tensorflow.python.keras.layers import BatchNormalization, Dropout
from tensorflow.python.keras.optimizers import Adam,SGD

BANDS = area_hsi_train_patches.shape[3]
NUM_CLS = train_one_hot.shape[1]
BATCH_SIZE = 25

area_hsi_model = Sequential()
area_hsi_model.add(InputLayer(input_shape=(HSI_PATCH_SIZE, HSI_PATCH_SIZE, BANDS)))
area_hsi_model.add(Conv2D(kernel_size=6, strides=2, filters=CONV1, padding='same', activation='relu', name='conv1'))
area_hsi_model.add(BatchNormalization())
area_hsi_model.add(MaxPooling2D(pool_size=2, strides=2))
area_hsi_model.add(Conv2D(kernel_size=5, strides=2, filters=CONV2, padding='same', activation='relu', name='conv2'))
area_hsi_model.add(BatchNormalization())
area_hsi_model.add(MaxPooling2D(pool_size=2, strides=2))


area_hsi_model.add(Flatten())
area_hsi_model.add(Dense(FC1, activation='relu'))
area_hsi_model.add(Dropout(0.6))
area_hsi_model.add(Dense(FC2, activation='relu'))
area_hsi_model.add(Dropout(0.4))
area_hsi_model.add(Dense(NUM_CLS, activation='softmax'))

In [0]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D, Dense, Flatten
from tensorflow.python.keras.layers import InputLayer
from tensorflow.python.keras.layers import  MaxPooling2D
from tensorflow.python.keras.layers import BatchNormalization, Dropout
from tensorflow.python.keras.optimizers import Adam,SGD

BANDS = area_lidar_train_patches.shape[3]
NUM_CLS = train_one_hot.shape[1]


area_lidar_model = Sequential()
area_lidar_model.add(InputLayer(input_shape=(LiDAR_PATCH_SIZE, LiDAR_PATCH_SIZE, BANDS)))
area_lidar_model.add(Conv2D(kernel_size=6, strides=2, filters=CONV1, padding='same', activation='relu', name='conv1'))
area_lidar_model.add(BatchNormalization())
area_lidar_model.add(MaxPooling2D(pool_size=2, strides=2))
area_lidar_model.add(Conv2D(kernel_size=5, strides=2, filters=CONV2, padding='same', activation='relu', name='conv2'))
area_lidar_model.add(BatchNormalization())
area_lidar_model.add(MaxPooling2D(pool_size=2, strides=2))


area_lidar_model.add(Flatten())
area_lidar_model.add(Dense(FC1, activation='relu'))
area_lidar_model.add(Dropout(0.7))
area_lidar_model.add(Dense(FC2, activation='relu'))
area_lidar_model.add(Dropout(0.5))
area_lidar_model.add(Dense(NUM_CLS, activation='softmax'))


In [0]:
area_hsi_model.load_weights('Models/area_hsi_model_weights.h5')
area_lidar_model.load_weights('Models/area_lidar_model_weights.h5')

In [0]:
from operator import truediv

def AA_andEachClassAccuracy(confusion_matrix):
    counter = confusion_matrix.shape[0]
    list_diag = np.diag(confusion_matrix)
    list_raw_sum = np.sum(confusion_matrix, axis=1)
    each_acc = np.nan_to_num(truediv(list_diag, list_raw_sum))
    average_acc = np.mean(each_acc)
    return each_acc, average_acc

In [0]:
test_cls = test_labels - 1
prediction = area_hsi_model.predict(area_hsi_test_patches).argmax(axis=-1)



from sklearn import metrics, preprocessing


overall_acc = metrics.accuracy_score(prediction, test_cls)
kappa = metrics.cohen_kappa_score(prediction, test_cls)
confusion_matrix = metrics.confusion_matrix(prediction, test_cls)
each_acc, average_acc = AA_andEachClassAccuracy(confusion_matrix) 


print("Overall Accuracy of testing sapmles : ",overall_acc)
print("Average Accuracy of testing samples : ",average_acc)
print("Kappa statistics of testing samples : ",kappa)
print("Each class accuracy of testing samples : ", each_acc)
print("Confusion matrix :", confusion_matrix)

Overall Accuracy of testing sapmles :  0.6269574485529229
Average Accuracy of testing samples :  0.6591057825766897
Kappa statistics of testing samples :  0.5951054853872203
Each class accuracy of testing samples :  [0.68176915 0.6295045  0.65667575 0.63526245 0.8633218  0.45791246
 0.65377856 0.60416667 0.75607287 0.90238095 0.53174061 0.40479616
 0.54054054 0.80866426 0.76      ]
Confusion matrix : [[632 112   0 130   0   1   0   0   0   0   0   0   0   0  52]
 [133 559   0 158   0   0  29   0   1   0   0   0   0   0   8]
 [  0   0 482   0   0   0   0   0   0   0   0   0   0   0 252]
 [ 57  84   0 472   0   0 123   7   0   0   0   0   0   0   0]
 [  2  13   0  18 998   0   0   3  33   0   0   0   0  16  73]
 [ 47  32   0   4   0 136  24  37   7   0   0   0   0   0  10]
 [  1  86   0 132   4   6 744  46  89   0  11   0  15   4   0]
 [  2   9   0  13   6   0   0 435 110  55   7  52  28   1   2]
 [  0   4   0  16  24   0  51   0 747  56  34  10  46   0   0]
 [  1   2   0  18   1   0   0

In [0]:
test_cls = test_labels - 1
prediction = area_lidar_model.predict(area_lidar_test_patches).argmax(axis=-1)



from sklearn import metrics, preprocessing


overall_acc = metrics.accuracy_score(prediction, test_cls)
kappa = metrics.cohen_kappa_score(prediction, test_cls)
confusion_matrix = metrics.confusion_matrix(prediction, test_cls)
each_acc, average_acc = AA_andEachClassAccuracy(confusion_matrix) 


print("Overall Accuracy of testing sapmles : ",overall_acc)
print("Average Accuracy of testing samples : ",average_acc)
print("Kappa statistics of testing samples : ",kappa)
print("Each class accuracy of testing samples : ", each_acc)
print("Confusion matrix :", confusion_matrix)

Overall Accuracy of testing sapmles :  0.5304583094203492
Average Accuracy of testing samples :  0.5364854006142565
Kappa statistics of testing samples :  0.4906388260322003
Each class accuracy of testing samples :  [0.47682119 0.40447154 0.59138187 0.51807229 0.77912254 0.40659341
 0.51507208 0.56845476 0.33020231 0.64369501 0.735269   0.47503201
 0.36090226 0.98969072 0.2525    ]
Confusion matrix : [[360  60   0 113  33   6  68   4  92   0   8   3   3   5   0]
 [ 81 398   7 123  55   0  86  26 102   0  21  44  19   7  15]
 [  0   1 398   0  41   0  12   0   0   0   0   1   0   0 220]
 [ 10  23   0 258  23   3  39  26  32   2   5  56  17   4   0]
 [ 21  14   0  38 515   3   0   0  45   0  22   0   1   2   0]
 [ 34   0   0  46   3 111   0   0  46  12   0  15   0   6   0]
 [  2  16   5 129  11   4 393  33  92   8   0   2   2   0  66]
 [ 20   0   0 144 110   8  89 710  13  32  22  95   0   6   0]
 [122 199   0 103  75   2 140  19 457  81  73  18  33   2  60]
 [ 20 199   0   5   2   0 127

In [0]:
from tensorflow.python.keras.models import Model
intermediate_layer_area_hsi_model = Model(area_hsi_model.layers[0].input,outputs=area_hsi_model.layers[6].output)
intermediate_layer_area_lidar_model = Model(area_lidar_model.layers[0].input,outputs=area_lidar_model.layers[6].output)

area_hsi_train_flatten = intermediate_layer_area_hsi_model.predict(area_hsi_train_patches)
area_lidar_train_flatten = intermediate_layer_area_lidar_model.predict(area_lidar_train_patches)

area_hsi_test_flatten = intermediate_layer_area_hsi_model.predict(area_hsi_test_patches)
area_lidar_test_flatten = intermediate_layer_area_lidar_model.predict(area_lidar_test_patches)

In [0]:
print(area_hsi_train_flatten.shape)
print(area_lidar_train_flatten.shape)
print(area_hsi_test_flatten.shape)
print(area_lidar_test_flatten.shape)

(2832, 400)
(2832, 400)
(12197, 400)
(12197, 400)


In [0]:
train_fusion = np.concatenate((area_hsi_train_flatten, area_lidar_train_flatten), axis=1)
test_fusion = np.concatenate((area_hsi_test_flatten, area_lidar_test_flatten), axis=1)
print(train_fusion.shape)
print(test_fusion.shape)

(2832, 800)
(12197, 800)


In [0]:
from tensorflow.keras.layers import concatenate
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D, Dense, Flatten
from tensorflow.python.keras.layers import InputLayer
from tensorflow.python.keras.layers import  MaxPooling2D
from tensorflow.python.keras.layers import BatchNormalization, Dropout
from tensorflow.python.keras.optimizers import Adam,SGD


fusion_model = Sequential()
fusion_model.add(Dense(512, input_dim=train_fusion.shape[1], activation='relu'))

fusion_model.add(Dropout(0.8))
fusion_model.add(Dense(256, activation='relu'))
fusion_model.add(Dropout(0.7))
fusion_model.add(Dense(128, activation='relu'))
fusion_model.add(Dropout(0.6))
fusion_model.add(Dense(NUM_CLS, activation='softmax'))

sgd = SGD(lr=LEARNING_RATE/2, decay=1e-6, momentum=0.9, nesterov=True)
fusion_model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

fusion_model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 512)               410112    
_________________________________________________________________
dropout_10 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_16 (Dense)             (None, 256)               131328    
_________________________________________________________________
dropout_11 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_17 (Dense)             (None, 128)               32896     
_________________________________________________________________
dropout_12 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_18 (Dense)             (None, 15)                1935      
Total para

In [0]:
history = fusion_model.fit(train_fusion, train_one_hot, batch_size=BATCH_SIZE, shuffle=True, epochs=50)

Epoch 1/50
2832/2832 [==============================] - 1s 201us/step - loss: 0.0217 - acc: 0.9965
Epoch 2/50
2832/2832 [==============================] - 1s 203us/step - loss: 0.0246 - acc: 0.9933
Epoch 3/50
2832/2832 [==============================] - 1s 195us/step - loss: 0.0236 - acc: 0.9940
Epoch 4/50
2832/2832 [==============================] - 1s 204us/step - loss: 0.0208 - acc: 0.9936
Epoch 5/50
2832/2832 [==============================] - 1s 195us/step - loss: 0.0156 - acc: 0.9968
Epoch 6/50
2832/2832 [==============================] - 1s 202us/step - loss: 0.0277 - acc: 0.9947
Epoch 7/50
2832/2832 [==============================] - 1s 192us/step - loss: 0.0289 - acc: 0.9940
Epoch 8/50
2832/2832 [==============================] - 1s 203us/step - loss: 0.0172 - acc: 0.9965
Epoch 9/50
2832/2832 [==============================] - 1s 198us/step - loss: 0.0149 - acc: 0.9965
Epoch 10/50
2832/2832 [==============================] - 1s 201us/step - loss: 0.0223 - acc: 0.9961
Epoch 11/

In [0]:
fusion_model.load_weights('Models/area_fusion_model_weights.h5')

In [0]:
test_cls = test_labels - 1
prediction = fusion_model.predict(test_fusion).argmax(axis=-1)



from sklearn import metrics, preprocessing

overall_acc = metrics.accuracy_score(prediction, test_cls)
kappa = metrics.cohen_kappa_score(prediction, test_cls)
confusion_matrix = metrics.confusion_matrix(prediction, test_cls)
each_acc, average_acc = AA_andEachClassAccuracy(confusion_matrix) 


print("Overall Accuracy of training sapmles : ",overall_acc)
print("Average Accuracy of training samples : ",average_acc)
print("Kappa statistics of training samples : ",kappa)
print("Each class accuracy of training samples : ", each_acc)
print("Confusion matrix :", confusion_matrix)

Overall Accuracy of training sapmles :  0.6750020496843486
Average Accuracy of training samples :  0.6886833845687763
Kappa statistics of training samples :  0.6475051484001848
Each class accuracy of training samples :  [0.50450958 0.71939328 0.60329531 0.71450151 0.87395737 0.33161954
 0.73243503 0.72567568 0.72075055 0.9627451  0.57584472 0.68235294
 0.71759259 0.90636704 0.55921053]
Confusion matrix : [[895 305   0 254   0   3  45  81  25  11  71   0   0   0  84]
 [ 53 664   0 147   8   0  25   0  24   0   0   1   0   0   1]
 [  0   0 476   0   0   0   0  13   0  19   0   0   8   0 273]
 [ 28  45   0 473   0   3 103   0   5   0   0   0   0   1   4]
 [ 26   8   0  30 943   0   0   5  56   0   0   0   0   0  11]
 [ 35   1   0   3   0 129  23  39  21  98  40   0   0   0   0]
 [  0  33   0  80   0   5 761  18 127   0   3   1  10   0   1]
 [  0   0   0  41  28   0  32 537  36   0   0  64   0   0   2]
 [  0   0   0   0  40   3  54   6 653  87  32   7  21   0   3]
 [  0   0   0   0   0   0

In [0]:
fusion_model.save_weights('Models/area_fusion_model_weights.h5')